name: Build and push blaiseio/acelink

on:
  push:
    branches: [master]
  release:
    types: [published]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: blaiseio
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          context: .
          platforms: linux/amd64  # linux/arm64 won't work because there's no acestream bin for this platform
          push: true
          tags: blaiseio/acelink:latest
      -
        name: Build and push
        uses: docker/build-push-action@v2
        if: ${{ github.event.release.tag_name }}
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: blaiseio/acelink:${{ github.event.release.tag_name }}
